language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: OMNdpWcb5emYrp112vxqHSGP8VX7vjjSYYLosIOW8W6mfVfYnjoGk6bsLICUE9FYZgwIUqFzYhPyvqO6HhsXdwgQIfCY1tWLcIHW6StRLkeOAzksnisf5GS/XO/SlSUko5XUwfbuGM13D1VOoJt7/n9+ql64qvGgi1vBoFLlr22IoduTh6SMaUMcUWf73WRLRO7QfRBSDn7xCvLcjdRdwQUj4VYIUrBSZFUDb9fS2GKol+bxu337elu6T2ao79XfvsxFlfUfLCIU31n6SDGkxi6v+muLLcKzRpdrwYEQwPFJi8/3N3y7GJzlK1Rl5pDZDH9mQU4FRcFAFcKSu/rsnV+AsPGiXNvUcDffpAZQAduHgQE4bYKG2t5Zxbgn94Qnp5kpQmqaoZshvWtKnI1iR8IcSda2SW8HDxbnixcR8p1mAIpqzpL256aVjmRmu3TZBdxWdCO2u3j6IHmjdPyZ7Nfa1hB6xlr/snwdZNj2ornyV1La/dNDJ607VZrUrpSqt9yMNw6TkeVZeRHPVx55Evrxts0oFOcGW7jKYxUE/w59oNA2oM+2HGW2U0SWtL3mgRbSxyko41rdlfyX+TmbmdoiC16YCSxo7kCQKMAPjCKvUenkNoxeiXGjhzjLdscz2IyAiHZ0ey0ZP/Xdm9Nny32FEOi8sI/mFyqnZ4jGYKY=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
